name: MasterPipeline

on:
  push:
    branches: [ master ]

jobs:
  compile:
    name: 编译
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装 JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # 3. 安装指定 Maven 3.6.3（官方未提供 3.6.3 预装，手动下载）
      - name: Install Maven 3.6.3
        run: |
          wget -q https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xzf apache-maven-3.6.3-bin.tar.gz
          sudo mv apache-maven-3.6.3 /opt/
          echo "/opt/apache-maven-3.6.3/bin" >> $GITHUB_PATH

      # 4. 构建（跳过测试）
      - name: Maven Build
        run: mvn -B clean package -Dmaven.test.skip=true

      # 5. 把产物上传为 Actions 制品（7 天自动清理）
      # 对应云效的 artifacts.name = BUILD_ARTIFACT
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BUILD_ARTIFACT
          path: |
            ./server/target/kkFileView-*.tar.gz
            ./server/target/kkFileView-*.zip
          retention-days: 7
